// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_control_neumaticos.Models;

#nullable disable

namespace api_control_neumaticos.Migrations
{
    [DbContext(typeof(ControlNeumaticosContext))]
    [Migration("20250122160147_AlertaUpdateCodigoAlertaFromStringToInt")]
    partial class AlertaUpdateCodigoAlertaFromStringToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_control_neumaticos.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CODIGO_ALERTA")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_ALERTA");

                    b.Property<DateTime>("FECHA_ALERTA")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ALERTA");

                    b.Property<int>("ID_NEUMATICO")
                        .HasColumnType("int")
                        .HasColumnName("ID_NEUMATICO");

                    b.HasKey("Id")
                        .HasName("PK__ALERTA__3214EC07");

                    b.HasIndex("ID_NEUMATICO");

                    b.ToTable("ALERTA", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.BitacoraNeumatico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CODIGO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FECHA")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDNeumatico")
                        .HasColumnType("int")
                        .HasColumnName("ID_NEUMATICO");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("OBSERVACION")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("IDNeumatico");

                    b.HasIndex("IDUsuario");

                    b.ToTable("BITACORA_NEUMATICO", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Bodega", b =>
                {
                    b.Property<int>("ID_BODEGA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_BODEGA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_BODEGA"));

                    b.Property<string>("NOMBRE_BODEGA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOMBRE_BODEGA");

                    b.HasKey("ID_BODEGA")
                        .HasName("PK__BODEGA__3F5C45522D15E7A1");

                    b.ToTable("BODEGA", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Kilometros", b =>
                {
                    b.Property<int>("ID_KILOMETRO_DIARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_KILOMETRO_DIARIO"));

                    b.Property<DateTime>("FECHA_REGISTRO")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_MOVIL")
                        .HasColumnType("int");

                    b.Property<int>("KILOMETRO")
                        .HasColumnType("int");

                    b.HasKey("ID_KILOMETRO_DIARIO");

                    b.HasIndex("ID_MOVIL");

                    b.ToTable("KILOMETROS", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Movil", b =>
                {
                    b.Property<int>("IdMovil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_MOVIL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovil"));

                    b.Property<int?>("CantidadNeumaticos")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD_NEUMATICOS");

                    b.Property<int>("Ejes")
                        .HasColumnType("int")
                        .HasColumnName("EJES");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESTADO");

                    b.Property<int?>("ID_BODEGA")
                        .HasColumnType("int")
                        .HasColumnName("ID_BODEGA");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("MARCA")
                        .IsFixedLength();

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("MODELO")
                        .IsFixedLength();

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasColumnName("PATENTE")
                        .IsFixedLength();

                    b.Property<int>("TipoMovil")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_MOVIL");

                    b.HasKey("IdMovil")
                        .HasName("PK__MOVIL__CEA90288602B00B0");

                    b.HasIndex("ID_BODEGA");

                    b.ToTable("MOVIL", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Neumatico", b =>
                {
                    b.Property<int>("ID_NEUMATICO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_NEUMATICO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NEUMATICO"));

                    b.Property<int>("CODIGO")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FECHA_INGRESO")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_INGRESO");

                    b.Property<DateTime?>("FECHA_SALIDA")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_SALIDA");

                    b.Property<int>("ID_BODEGA")
                        .HasColumnType("int")
                        .HasColumnName("ID_BODEGA");

                    b.Property<int>("KM_TOTAL")
                        .HasColumnType("int")
                        .HasColumnName("KM_TOTAL");

                    b.Property<int?>("MOVIL_ASIGNADO_ID")
                        .HasColumnType("int")
                        .HasColumnName("MOVIL_ASIGNADO");

                    b.Property<string>("TIPO_NEUMATICO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TIPO_NEUMATICO");

                    b.Property<string>("UBICACION")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("UBICACION")
                        .IsFixedLength();

                    b.HasKey("ID_NEUMATICO")
                        .HasName("PK__NEUMATIC__BEA984E3CB53E60C");

                    b.HasIndex("ID_BODEGA");

                    b.HasIndex("MOVIL_ASIGNADO_ID");

                    b.ToTable("NEUMATICOS", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Tabla", b =>
                {
                    b.Property<int>("CodTabla")
                        .HasColumnType("int")
                        .HasColumnName("COD_TABLA");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.HasKey("CodTabla", "Codigo")
                        .HasName("PK__TABLA__B22008D28B9CFED8");

                    b.ToTable("TABLA", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("APELLIDOS");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLAVE");

                    b.Property<int>("CodEstado")
                        .HasColumnType("int")
                        .HasColumnName("COD_ESTADO");

                    b.Property<int>("CodigoPerfil")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_PERFIL");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("CORREO");

                    b.Property<int>("ID_BODEGA")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMBRES");

                    b.HasKey("IdUsuario")
                        .HasName("PK__USUARIO__91136B9039C79A3A");

                    b.HasIndex("ID_BODEGA");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Alerta", b =>
                {
                    b.HasOne("api_control_neumaticos.Models.Neumatico", "Neumatico")
                        .WithMany()
                        .HasForeignKey("ID_NEUMATICO")
                        .IsRequired();

                    b.Navigation("Neumatico");
                });

            modelBuilder.Entity("api_control_neumaticos.Models.BitacoraNeumatico", b =>
                {
                    b.HasOne("api_control_neumaticos.Models.Neumatico", "Neumatico")
                        .WithMany()
                        .HasForeignKey("IDNeumatico")
                        .IsRequired();

                    b.HasOne("api_control_neumaticos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .IsRequired();

                    b.Navigation("Neumatico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Kilometros", b =>
                {
                    b.HasOne("api_control_neumaticos.Models.Movil", "Movil")
                        .WithMany()
                        .HasForeignKey("ID_MOVIL")
                        .IsRequired();

                    b.Navigation("Movil");
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Movil", b =>
                {
                    b.HasOne("api_control_neumaticos.Models.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("ID_BODEGA");

                    b.Navigation("Bodega");
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Neumatico", b =>
                {
                    b.HasOne("api_control_neumaticos.Models.Bodega", "BODEGA")
                        .WithMany()
                        .HasForeignKey("ID_BODEGA")
                        .IsRequired();

                    b.HasOne("api_control_neumaticos.Models.Movil", "MOVIL_ASIGNADO")
                        .WithMany()
                        .HasForeignKey("MOVIL_ASIGNADO_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BODEGA");

                    b.Navigation("MOVIL_ASIGNADO");
                });

            modelBuilder.Entity("api_control_neumaticos.Models.Usuario", b =>
                {
                    b.HasOne("api_control_neumaticos.Models.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("ID_BODEGA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");
                });
#pragma warning restore 612, 618
        }
    }
}
